server:
  port: 8080

database:
  dbhost: "127.0.0.1"
  dbdriver: "postgres"
  dbport: "3306"
  dbname: "userame"
  dbuser: "password"
  dbpassword: "5432"

MAILGUN_API_KEY: ""
MAILGUN_DOMAIN: ""

JWT_SECRET:  ""

